Update conditionals.yml

diff --git a/.github/workflows/conditionals.yml b/.github/workflows/conditionals.yml
--- a/.github/workflows/conditionals.yml
+++ b/.github/workflows/conditionals.yml
@@ -13,5 +13,8 @@ jobs:
     if: github.event_name != 'pull_request'
     runs-on: ubuntu-latest
     steps:
-      - name: only run on push events
-        run: echo "Only run on push events"
+      - name: step with continue-on-error
+        run: |
+          echo "This step will fail"
+          exit 1
+        continue-on-error: true
